name: exa_jaffle_shop
version: "1.0.0"
config-version: 2

profile: exa_jaffle_shop

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["data-tests"]

target-path: "target"
clean-targets:
  - target
  - dbt_packages

quoting:
  database: false
  schema: false
  identifier: false

seeds:
  exa_jaffle_shop:
    +schema: raw

models:
  exa_jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
