version: 2

sources:
  - name: ecom
    schema: "{{ target.schema ~ '_RAW' }}"
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_items
      - name: raw_products
      - name: raw_stores
      - name: raw_supplies
